vich_uploader:
    db_driver: orm

    mappings:
       cv:
           uri_prefix: /uploads/cv
           upload_destination: '%kernel.project_dir%/public/uploads/cv'
           namer: 
            service: Vich\UploaderBundle\Naming\HashNamer
            options: { algorithm: 'sha256', length: 50 }